# This template uses jdk8 for verifying and deploying images
image: maven:3.6.3-jdk-11

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  
before_script:
    - cd KodeX/

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
#cache:
#  paths:
#    - .m2/repository
#  key: $CI_COMMIT_REF_SLUG
  
stages:
  - compile
  - test
  - checkstyle

java-compile:
  stage: compile
  script:
    - 'mvn $MAVEN_CLI_OPTS compile'
    
java-test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test'
    - 'cat target/jacoco-report/index.html'
      
java-checkstyle:
  stage: checkstyle
  script:
    - 'mvn $MAVEN_CLI_OPTS checkstyle:check'
  allow_failure: true